import { HeaderMain } from "@/components/layout/headerMain";
import "./globals.css";
import { Roboto } from "next/font/google";

const roboto = Roboto({ subsets: ["latin"], weight: "500" });

export const metadata = {
  title: "GMZ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={roboto.className} style={{ position: "relative" }}>
        <HeaderMain />
        {children}
      </body>
    </html>
  );
}
