import { HeaderMain } from "@/components/layout/headerMain";
import "./globals.css";

export const metadata = {
  title: "GMZ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body style={{ fontFamily: "Verdana", position: "relative" }}>
        <HeaderMain />
        {children}
      </body>
    </html>
  );
}
